# Generated by Django 5.2.16 on 2026-09-05 03:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('corte', '0006_registrocorte_metros_cortado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvioProducao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('destino', models.CharField(help_text='Facção/prestador que recebe — sugerido a partir do destino_costura da OP, editável.', max_length=120, verbose_name='Enviado para')),
                ('quantidade_pecas', models.PositiveIntegerField(verbose_name='Peças enviadas')),
                ('observacao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='envios_producao_criados', to=settings.AUTH_USER_MODEL)),
                ('programacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='envios_producao', to='corte.programacaocorte')),
            ],
            options={
                'verbose_name': 'Envio para produção',
                'verbose_name_plural': 'Envios para produção',
                'ordering': ['-data', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='FechamentoOP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faturamento_confirmado', models.BooleanField(default=False)),
                ('faturamento_confirmado_em', models.DateTimeField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True)),
                ('faturamento_confirmado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fechamentos_confirmados', to=settings.AUTH_USER_MODEL)),
                ('programacao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fechamento', to='corte.programacaocorte')),
            ],
            options={
                'verbose_name': 'Fechamento de OP',
                'verbose_name_plural': 'Fechamentos de OP',
            },
        ),
        migrations.CreateModel(
            name='RetornoProducao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('quantidade_pecas', models.PositiveIntegerField(verbose_name='Peças retornadas (prontas)')),
                ('retalho_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Retalho da produção (kg)')),
                ('observacao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retornos_producao_criados', to=settings.AUTH_USER_MODEL)),
                ('programacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retornos_producao', to='corte.programacaocorte')),
            ],
            options={
                'verbose_name': 'Retorno de produção',
                'verbose_name_plural': 'Retornos de produção',
                'ordering': ['-data', '-criado_em'],
            },
        ),
    ]
