# Generated by Django 5.2.16 on 2026-09-14 12:49

from django.conf import settings
from django.db import migrations, models

from integracao.normalize import normalize_text


def marcar_envios_internos(apps, schema_editor):
    """Os envios que já existiam nasceram OSE (o default do campo). Os que
    foram pra costura da própria casa são OSI — mesma heurística que o
    formulário usa daqui pra frente (controle_op/models.py::
    tipo_os_sugerido). Só um palpite de partida: o tipo continua editável."""
    EnvioProducao = apps.get_model("controle_op", "EnvioProducao")
    ids = [e.id for e in EnvioProducao.objects.all()
           if normalize_text(e.destino) == "COSTURA INTERNA"]
    EnvioProducao.objects.filter(id__in=ids).update(tipo="OSI")


class Migration(migrations.Migration):

    dependencies = [
        ('controle_op', '0001_initial'),
        ('corte', '0006_registrocorte_metros_cortado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='envioproducao',
            name='numero',
            field=models.CharField(blank=True, db_index=True, help_text='Número que o ERP deu pra esta OS. Pode ficar vazio agora (o envio físico às vezes acontece antes da OS ser emitida), mas vira pendência que impede a baixa da OP.', max_length=30, verbose_name='Número da OS (ERP)'),
        ),
        migrations.AddField(
            model_name='envioproducao',
            name='tipo',
            field=models.CharField(choices=[('OSE', 'OSE — industrialização externa (facção)'), ('OSI', 'OSI — industrialização interna')], default='OSE', max_length=3, verbose_name='Tipo de OS'),
        ),
        migrations.RunPython(marcar_envios_internos, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='envioproducao',
            constraint=models.UniqueConstraint(condition=models.Q(('numero', ''), _negated=True), fields=('tipo', 'numero'), name='envio_os_numero_unico', violation_error_message='Já existe uma OS com este tipo e número.'),
        ),
    ]
