# Generated by Django 5.2.16 on 2026-09-14 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_op', '0002_envioproducao_numero_envioproducao_tipo_and_more'),
        ('corte', '0006_registrocorte_metros_cortado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroProducao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data da produção')),
                ('quantidade_pecas', models.PositiveIntegerField(verbose_name='Peças produzidas (1ª qualidade)')),
                ('qualidade_segunda_pecas', models.PositiveIntegerField(default=0, verbose_name='Peças de 2ª qualidade')),
                ('retalho_kg', models.DecimalField(blank=True, decimal_places=2, help_text="Deixe vazio se não foi pesado — vazio não é zero, e o balanço de material (Fase 4) trata ausência como dado faltante, não como 'não houve retalho'.", max_digits=10, null=True, verbose_name='Retalho da produção (kg)')),
                ('observacao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='producoes_criadas', to=settings.AUTH_USER_MODEL)),
                ('programacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_producao', to='corte.programacaocorte')),
            ],
            options={
                'verbose_name': 'Apontamento de produção',
                'verbose_name_plural': 'Apontamentos de produção',
                'ordering': ['-data', '-criado_em'],
            },
        ),
    ]
