# Generated by Django 5.2.16 on 2026-09-14 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_op', '0003_registroproducao'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroproducao',
            name='destino',
            field=models.CharField(blank=True, help_text='Só pede quando esta OP já foi enviada pra mais de um prestador.', max_length=120, verbose_name='Prestador'),
        ),
        migrations.AddField(
            model_name='retornoproducao',
            name='destino',
            field=models.CharField(blank=True, help_text='Só pede quando esta OP já foi enviada pra mais de um prestador.', max_length=120, verbose_name='Prestador'),
        ),
    ]
