# Generated by Django 5.2.16 on 2026-09-15 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_op', '0003_registroproducao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fechamentoop',
            name='balanco_snapshot',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fechamentoop',
            name='balanco_status',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='fechamentoop',
            name='motivo_divergencia',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='fechamentoop',
            name='op_baixada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fechamentoop',
            name='op_baixada_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fechamentoop',
            name='op_baixada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ops_baixadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
