# Generated by Django 5.2.16 on 2026-09-15 11:10

import controle_op.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_op', '0004_registroproducao_destino_retornoproducao_destino'),
        ('corte', '0006_registrocorte_metros_cortado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('telefone', models.CharField(blank=True, help_text='Só dígitos, com DDI+DDD (ex.: 5514999998888) — usado pro link de wa.me.', max_length=20, verbose_name='Telefone (WhatsApp)')),
                ('token', models.CharField(default=controle_op.models._gerar_token, editable=False, max_length=43, unique=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Prestador',
                'verbose_name_plural': 'Prestadores',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='registroproducao',
            name='criado_por_nome',
            field=models.CharField(blank=True, max_length=120, verbose_name='Nome de quem preencheu (prestador)'),
        ),
        migrations.AddField(
            model_name='registroproducao',
            name='origem',
            field=models.CharField(choices=[('INTERNO', 'Lançado pela Zanattex'), ('PRESTADOR', 'Lançado pelo prestador (link sem login)')], default='INTERNO', max_length=10),
        ),
        migrations.AlterField(
            model_name='registroproducao',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='producoes_criadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='registroproducao',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('criado_por__isnull', False), ('criado_por_nome', ''), ('origem', 'INTERNO')), models.Q(('criado_por__isnull', True), ('origem', 'PRESTADOR'), models.Q(('criado_por_nome', ''), _negated=True)), _connector='OR'), name='producao_autor_consistente_com_origem'),
        ),
    ]
