# Generated by Django 5.2.16 on 2026-09-15 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_op', '0004_fechamentoop_balanco_snapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fechamentoop',
            name='quantidade_faturada',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
