# Generated by Django 5.2.16 on 2026-09-15 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_op', '0005_prestador_registroproducao_criado_por_nome_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaPrestador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.CharField(max_length=120)),
                ('cliente', models.CharField(blank=True, max_length=120)),
                ('meta_pecas', models.PositiveIntegerField(verbose_name='Meta (peças)')),
                ('ativo', models.BooleanField(default=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('prestador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metas', to='controle_op.prestador')),
            ],
            options={
                'verbose_name': 'Meta do prestador',
                'verbose_name_plural': 'Metas dos prestadores',
                'ordering': ['prestador__nome', 'produto', 'cliente'],
                'constraints': [models.UniqueConstraint(fields=('prestador', 'produto', 'cliente'), name='meta_prestador_produto_cliente_unico')],
            },
        ),
    ]
