# Generated by Django 5.2.16 on 2026-09-16 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controle_op', '0005_fechamentoop_quantidade_faturada'),
        ('controle_op', '0006_metaprestador'),
    ]

    operations = [
    ]
