# Generated by Django 5.2.16 on 2026-08-06 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnvioDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('corte', 'Corte'), ('producao', 'Produção Diária')], max_length=10)),
                ('data_referencia', models.DateField(verbose_name='Data de referência (D-1)')),
                ('status', models.CharField(choices=[('aviso', 'Aviso de pendência enviado'), ('enviado', 'Relatório definitivo enviado')], max_length=10)),
                ('detalhe', models.TextField(blank=True, default='', verbose_name='Detalhe')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Envio diário',
                'verbose_name_plural': 'Envios diários',
                'ordering': ['-data_referencia', 'tipo'],
                'unique_together': {('tipo', 'data_referencia')},
            },
        ),
    ]
