# Generated by Django 5.2.16 on 2026-08-06 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enviodiario',
            name='detalhe',
            field=models.TextField(blank=True, default='', help_text='Última lista de pendências enviada (pra comparar e não repetir e-mail parcial idêntico).', verbose_name='Detalhe'),
        ),
        migrations.AlterField(
            model_name='enviodiario',
            name='status',
            field=models.CharField(choices=[('parcial', 'Relatório parcial enviado'), ('completo', 'Relatório definitivo enviado')], max_length=10),
        ),
    ]
