# Generated by Django 5.2.16 on 2026-07-23 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True, verbose_name='Nome')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cliente (frete)',
                'verbose_name_plural': 'Clientes (frete)',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='CalculoFrete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data do cálculo')),
                ('destino', models.CharField(blank=True, default='', max_length=300)),
                ('distancia_km', models.FloatField(blank=True, null=True)),
                ('ida_volta', models.BooleanField(default=False)),
                ('veiculo', models.CharField(blank=True, default='', max_length=200)),
                ('cavalo', models.CharField(blank=True, default='', max_length=200)),
                ('diesel', models.FloatField(default=0)),
                ('motorista', models.FloatField(default=0)),
                ('pedagio', models.FloatField(default=0)),
                ('manutencao', models.FloatField(default=0)),
                ('arla', models.FloatField(default=0)),
                ('depreciacao', models.FloatField(default=0)),
                ('seguro', models.FloatField(default=0)),
                ('gris', models.FloatField(default=0)),
                ('multa', models.FloatField(default=0)),
                ('valor_carga', models.FloatField(default=0)),
                ('risco_pct', models.FloatField(default=0)),
                ('impostos_pct', models.FloatField(default=0)),
                ('impostos_valor', models.FloatField(default=0)),
                ('margem_pct', models.FloatField(default=0)),
                ('valor_frete', models.FloatField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calculos', to='frete.cliente')),
            ],
            options={
                'verbose_name': 'Cálculo de frete',
                'verbose_name_plural': 'Cálculos de frete',
                'ordering': ['-data', '-criado_em'],
            },
        ),
    ]
