# Generated by Django 5.2.16 on 2026-07-27 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FonteSincronizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(max_length=100, unique=True, verbose_name='Chave')),
                ('tabela', models.CharField(max_length=100, verbose_name='Tabela')),
                ('label', models.CharField(max_length=200, verbose_name='Nome')),
                ('status', models.CharField(choices=[('OK', 'OK'), ('ERRO', 'Erro'), ('NUNCA', 'Nunca sincronizada')], default='NUNCA', max_length=10)),
                ('linhas', models.PositiveIntegerField(blank=True, null=True, verbose_name='Linhas')),
                ('ultima_sincronizacao', models.DateTimeField(blank=True, null=True, verbose_name='Última sincronização')),
                ('erro', models.TextField(blank=True, default='', verbose_name='Erro')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fonte sincronizada',
                'verbose_name_plural': 'Fontes sincronizadas',
                'ordering': ['label'],
            },
        ),
    ]
