# Generated by Django 5.2.16 on 2026-08-18 19:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setor', models.CharField(blank=True, choices=[('PCP', 'PCP'), ('CORTE', 'Corte'), ('RH', 'Recursos Humanos'), ('COMERCIAL', 'Comercial'), ('LOGISTICA', 'Logística'), ('CONTROLADORIA', 'Controladoria')], help_text='Em branco = sem restrição extra de módulos (vê tudo, igual a hoje).', max_length=20, verbose_name='Setor')),
                ('unidade_corte', models.CharField(blank=True, choices=[('AREALVA_MANTA', 'Manta Arealva'), ('IACANGA_MANTA', 'Manta Iacanga'), ('LENCOL', 'Lençol'), ('CORTINA', 'Cortina'), ('ITAJU', 'Itaju')], help_text='Só relevante quando o setor é Corte — escopa a fila de Gestão de Corte.', max_length=20, verbose_name='Unidade de corte')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de usuário',
                'verbose_name_plural': 'Perfis de usuário',
            },
        ),
    ]
