# Generated by Django 5.2.16 on 2026-09-21 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0002_perfilusuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='setor',
            field=models.CharField(blank=True, choices=[('PCP', 'PCP'), ('CORTE', 'Corte'), ('RH', 'Recursos Humanos'), ('COMERCIAL', 'Comercial'), ('LOGISTICA', 'Logística'), ('CONTROLADORIA', 'Controladoria'), ('FISCAL', 'Fiscal')], help_text='Em branco = sem restrição extra de módulos (vê tudo, igual a hoje).', max_length=20, verbose_name='Setor'),
        ),
    ]
