# Generated by Django 5.2.16 on 2026-08-18 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramacaoCorte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido', models.CharField(db_index=True, max_length=50, verbose_name='Pedido')),
                ('op_interna', models.CharField(blank=True, max_length=50, verbose_name='OP Interna')),
                ('oc', models.CharField(blank=True, max_length=50, verbose_name='OC')),
                ('cliente', models.CharField(max_length=120)),
                ('categoria', models.CharField(blank=True, max_length=60)),
                ('produto', models.CharField(max_length=120)),
                ('tamanho', models.CharField(blank=True, max_length=30)),
                ('saldo_carteira_snap', models.PositiveIntegerField(verbose_name='Saldo em aberto no momento')),
                ('qnt_programada', models.PositiveIntegerField(verbose_name='Qtd. a programar')),
                ('semana', models.CharField(max_length=10)),
                ('local', models.CharField(choices=[('GIATTEX', 'Giattex (Iacanga)'), ('ZANATTEX', 'Zanattex (Arealva)'), ('LENCOL', 'Lençol (Arealva)')], max_length=20)),
                ('destino_costura', models.CharField(help_text='Facção/costura que recebe o corte — mesma lista de producao.faccao_loader.load_faccoes().', max_length=120, verbose_name='Destino (costura)')),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('prev_industrializacao', models.DateField(blank=True, null=True, verbose_name='Previsão de industrialização')),
                ('data_finalizado', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PARCIAL', 'Parcial'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=20)),
                ('observacao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programacoes_criadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Programação de corte',
                'verbose_name_plural': 'Programações de corte',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='RegistroCorte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidade', models.CharField(choices=[('AREALVA_MANTA', 'Manta Arealva'), ('IACANGA_MANTA', 'Manta Iacanga'), ('LENCOL', 'Lençol'), ('CORTINA', 'Cortina'), ('ITAJU', 'Itaju')], max_length=20)),
                ('data', models.DateField()),
                ('quantidade_pecas', models.PositiveIntegerField(verbose_name='Peças cortadas')),
                ('kg_cortado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Kg cortado')),
                ('retalho_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Retalho (kg)')),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_corte', to=settings.AUTH_USER_MODEL)),
                ('programacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros', to='corte.programacaocorte')),
            ],
            options={
                'verbose_name': 'Registro de corte',
                'verbose_name_plural': 'Registros de corte',
                'ordering': ['-data', '-criado_em'],
            },
        ),
        migrations.AddIndex(
            model_name='programacaocorte',
            index=models.Index(fields=['pedido'], name='corte_progr_pedido_b17831_idx'),
        ),
        migrations.AddIndex(
            model_name='programacaocorte',
            index=models.Index(fields=['semana', 'local'], name='corte_progr_semana_3bf332_idx'),
        ),
    ]
