# Generated by Django 5.2.16 on 2026-08-18 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corte', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='programacaocorte',
            name='origem',
            field=models.CharField(choices=[('SISTEMA', 'Sistema'), ('IMPORTACAO', 'Importação (planilha)')], default='SISTEMA', max_length=20),
        ),
    ]
