# Generated by Django 5.2.16 on 2026-08-18 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corte', '0002_programacaocorte_origem'),
    ]

    operations = [
        migrations.AddField(
            model_name='programacaocorte',
            name='reprogramada_de',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reprogramacoes', to='corte.programacaocorte'),
        ),
        migrations.AlterField(
            model_name='programacaocorte',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('PARCIAL', 'Parcial'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado'), ('REPROGRAMADO', 'Reprogramado')], default='PENDENTE', max_length=20),
        ),
    ]
