# Generated by Django 5.2.16 on 2026-08-19 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corte', '0003_programacaocorte_reprogramada_de_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programacaocorte',
            name='destino_costura',
            field=models.CharField(help_text='Facção/produção que recebe o corte — mesma lista de producao.faccao_loader.load_faccoes().', max_length=120, verbose_name='Destino (produção)'),
        ),
    ]
