# Generated by Django 5.2.16 on 2026-08-19 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corte', '0004_alter_programacaocorte_destino_costura'),
    ]

    operations = [
        migrations.AddField(
            model_name='programacaocorte',
            name='unidade_corte',
            field=models.CharField(blank=True, choices=[('AREALVA_MANTA', 'Manta Arealva'), ('IACANGA_MANTA', 'Manta Iacanga'), ('LENCOL', 'Lençol'), ('CORTINA', 'Cortina'), ('ITAJU', 'Itaju')], help_text='Unidade real que vai cortar — granularidade maior que `local` (ex.: local=ZANATTEX pode ser Manta Arealva, Cortina ou Itaju). É o que a tela de Nova Programação pede pra escolher, e o que a fila de Gestão de Corte usa pra filtrar sem ambiguidade. Em branco = OP antiga (backfill/pré-migração), a fila cai de volta no agrupamento por local.', max_length=20, verbose_name='Unidade de corte'),
        ),
        migrations.AlterField(
            model_name='programacaocorte',
            name='local',
            field=models.CharField(choices=[('GIATTEX', 'Giattex (Iacanga)'), ('ZANATTEX', 'Zanattex (Arealva)'), ('LENCOL', 'Lençol (Arealva)')], help_text='Derivado automaticamente de `unidade_corte` — ver UNIDADE_TO_LOCAL abaixo. Continua existindo pra não quebrar filtros/relatórios já agrupados por local (ex.: relatório pro grupo do PCP).', max_length=20),
        ),
    ]
