# Generated by Django 5.2.16 on 2026-08-19 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corte', '0005_programacaocorte_unidade_corte_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrocorte',
            name='metros_cortado',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Só Lençol — medido do rolo, não é sempre igual a peças×metros_por_peça (pode ter perda/emenda no meio).', max_digits=10, null=True, verbose_name='Metros cortados'),
        ),
        migrations.AlterField(
            model_name='registrocorte',
            name='kg_cortado',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Manta/Cobertor — pesado na balança. Lençol usa `metros_cortado` em vez disso (não pesa em kg, mede em metros).', max_digits=10, null=True, verbose_name='Kg cortado'),
        ),
        migrations.CreateModel(
            name='Cortador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('unidade_corte', models.CharField(choices=[('AREALVA_MANTA', 'Manta Arealva'), ('IACANGA_MANTA', 'Manta Iacanga'), ('LENCOL', 'Lençol'), ('CORTINA', 'Cortina'), ('ITAJU', 'Itaju')], max_length=20)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Cortador',
                'verbose_name_plural': 'Cortadores',
                'ordering': ['nome'],
                'unique_together': {('nome', 'unidade_corte')},
            },
        ),
        migrations.CreateModel(
            name='EstacaoCorte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('unidade_corte', models.CharField(choices=[('AREALVA_MANTA', 'Manta Arealva'), ('IACANGA_MANTA', 'Manta Iacanga'), ('LENCOL', 'Lençol'), ('CORTINA', 'Cortina'), ('ITAJU', 'Itaju')], max_length=20)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Estação de corte',
                'verbose_name_plural': 'Estações de corte',
                'ordering': ['nome'],
                'unique_together': {('nome', 'unidade_corte')},
            },
        ),
    ]
