# Generated by Django 5.2.16 on 2026-09-14 20:56
# Editado à mão: makemigrations detectou a troca de prev_industrializacao por
# prev_corte como remove+add (perderia os valores já gravados em produção).
# RenameField preserva o dado — o campo continua com o mesmo significado
# ("data prevista", só que agora de corte em vez de industrialização),
# então é uma renomeação de verdade, não um campo novo.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corte', '0006_registrocorte_metros_cortado_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programacaocorte',
            old_name='prev_industrializacao',
            new_name='prev_corte',
        ),
        migrations.AlterField(
            model_name='programacaocorte',
            name='prev_corte',
            field=models.DateField(blank=True, null=True, verbose_name='Previsão de corte'),
        ),
        migrations.AddField(
            model_name='programacaocorte',
            name='data_entrada_carteira',
            field=models.DateField(blank=True, null=True, verbose_name='Entrada na Carteira'),
        ),
    ]
