# Generated by Django 5.2.16 on 2026-09-14 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corte', '0007_remove_programacaocorte_prev_industrializacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='programacaocorte',
            name='kg_requisitado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Kg requisitado (NF/PDF da OP)'),
        ),
        migrations.AddField(
            model_name='programacaocorte',
            name='metros_requisitado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Metros requisitados (NF/PDF da OP)'),
        ),
        migrations.AddField(
            model_name='registrocorte',
            name='baby_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Baby (kg)'),
        ),
        migrations.AddField(
            model_name='registrocorte',
            name='gramatura',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='Gramatura (kg/peça)'),
        ),
        migrations.AddField(
            model_name='registrocorte',
            name='plastico_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Plástico (kg)'),
        ),
        migrations.AddField(
            model_name='registrocorte',
            name='tubo_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Tubo (kg)'),
        ),
    ]
