# Generated by Django 5.2.16 on 2026-09-14 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportacaoCarteira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_arquivo', models.CharField(max_length=255)),
                ('linhas_importadas', models.PositiveIntegerField()),
                ('linhas_ignoradas', models.PositiveIntegerField(default=0)),
                ('avisos', models.JSONField(blank=True, default=list)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='importacoes_carteira', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Importação de carteira',
                'verbose_name_plural': 'Importações de carteira',
                'ordering': ['-criado_em'],
            },
        ),
    ]
