# Generated by Django 5.2.16 on 2026-09-17 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carteira', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='importacaocarteira',
            name='valor_total',
            field=models.FloatField(default=0),
        ),
    ]
