# Generated by Django 5.2.16 on 2026-09-21 19:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Razão social')),
                ('cnpj', models.CharField(db_index=True, max_length=14, unique=True, verbose_name='CNPJ')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='NotaFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada (remessa recebida)'), ('SAIDA', 'Saída (retorno)')], db_index=True, max_length=10)),
                ('status', models.CharField(choices=[('OK', 'OK'), ('PENDENTE', 'Pendente de conferência'), ('ERRO', 'Erro no processamento')], db_index=True, default='OK', max_length=10)),
                ('chave_acesso', models.CharField(db_index=True, max_length=44, unique=True, verbose_name='Chave de acesso')),
                ('n_nf', models.CharField(db_index=True, max_length=20, verbose_name='Número da NF')),
                ('serie', models.CharField(blank=True, max_length=5, verbose_name='Série')),
                ('nat_op', models.CharField(blank=True, max_length=120, verbose_name='Natureza da operação')),
                ('data_emissao', models.DateTimeField(verbose_name='Data de emissão')),
                ('emit_cnpj', models.CharField(max_length=14, verbose_name='CNPJ emitente')),
                ('emit_nome', models.CharField(blank=True, max_length=200, verbose_name='Emitente')),
                ('dest_cnpj', models.CharField(max_length=14, verbose_name='CNPJ destinatário')),
                ('dest_nome', models.CharField(blank=True, max_length=200, verbose_name='Destinatário')),
                ('centro_custo', models.CharField(blank=True, db_index=True, max_length=120, verbose_name='Centro de custo')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Valor total')),
                ('arquivo_origem', models.CharField(blank=True, max_length=255, verbose_name='Arquivo de origem')),
                ('importado_em', models.DateTimeField(auto_now_add=True)),
                ('xml_bruto', models.TextField(blank=True, verbose_name='XML original')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas', to='fiscal.cliente')),
                ('importado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nota fiscal',
                'verbose_name_plural': 'Notas fiscais',
                'ordering': ['-data_emissao'],
            },
        ),
        migrations.CreateModel(
            name='NotaFiscalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_item', models.PositiveSmallIntegerField(verbose_name='Nº do item')),
                ('c_prod', models.CharField(db_index=True, max_length=60, verbose_name='Código do produto')),
                ('x_prod', models.CharField(max_length=300, verbose_name='Descrição')),
                ('ncm', models.CharField(blank=True, db_index=True, max_length=8, verbose_name='NCM')),
                ('cfop', models.CharField(db_index=True, max_length=4, verbose_name='CFOP')),
                ('u_com', models.CharField(blank=True, max_length=10, verbose_name='Unidade')),
                ('q_com', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Quantidade')),
                ('v_un_com', models.DecimalField(decimal_places=10, default=0, max_digits=16, verbose_name='Valor unitário')),
                ('v_prod', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Valor total do item')),
                ('inf_ad_prod', models.CharField(blank=True, db_index=True, help_text='Nº da NF de entrada de onde esse item está sendo baixado (só em itens de saída).', max_length=60, verbose_name='infAdProd')),
                ('tipo_retorno', models.CharField(choices=[('DEVOLUCAO_INSUMO', 'Devolução de insumo não utilizado'), ('ENTREGA_PRODUTO', 'Entrega de produto industrializado'), ('NA', 'Não aplicável (item de entrada)')], default='NA', max_length=20)),
                ('saldo_atual', models.DecimalField(blank=True, decimal_places=4, help_text='Só preenchido em itens de entrada — quantidade ainda não devolvida.', max_digits=14, null=True, verbose_name='Saldo atual')),
                ('nota_fiscal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='fiscal.notafiscal')),
            ],
            options={
                'verbose_name': 'Item de nota fiscal',
                'verbose_name_plural': 'Itens de nota fiscal',
                'ordering': ['nota_fiscal', 'n_item'],
            },
        ),
        migrations.CreateModel(
            name='PendenciaMatching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(choices=[('NF_NAO_ENCONTRADA', 'NF de entrada (infAdProd) não encontrada'), ('ITEM_AMBIGUO', 'Mais de um item da entrada é candidato'), ('ITEM_NAO_ENCONTRADO', 'Nenhum item da entrada bate por NCM/código'), ('SALDO_INSUFICIENTE', 'Devolução maior que o saldo disponível'), ('CNPJ_SEM_CLIENTE', 'CNPJ do XML sem Cliente cadastrado')], max_length=30)),
                ('detalhe', models.TextField(blank=True, verbose_name='Detalhe')),
                ('resolvido', models.BooleanField(default=False)),
                ('resolvido_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('resolvido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('saida_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pendencias', to='fiscal.notafiscalitem')),
            ],
            options={
                'verbose_name': 'Pendência de casamento fiscal',
                'verbose_name_plural': 'Pendências de casamento fiscal',
                'ordering': ['resolvido', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Vinculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_baixada', models.DecimalField(decimal_places=4, max_digits=14)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('entrada_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vinculos_entrada', to='fiscal.notafiscalitem')),
                ('saida_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_saida', to='fiscal.notafiscalitem')),
            ],
            options={
                'verbose_name': 'Vínculo (baixa)',
                'verbose_name_plural': 'Vínculos (baixas)',
            },
        ),
        migrations.AddIndex(
            model_name='notafiscal',
            index=models.Index(fields=['cliente', 'n_nf'], name='fiscal_nota_cliente_6a0e7e_idx'),
        ),
        migrations.AddIndex(
            model_name='notafiscal',
            index=models.Index(fields=['cliente', 'tipo', 'status'], name='fiscal_nota_cliente_60406e_idx'),
        ),
        migrations.AddIndex(
            model_name='notafiscalitem',
            index=models.Index(fields=['nota_fiscal', 'ncm'], name='fiscal_nota_nota_fi_853b10_idx'),
        ),
        migrations.AddIndex(
            model_name='notafiscalitem',
            index=models.Index(fields=['nota_fiscal', 'c_prod'], name='fiscal_nota_nota_fi_2c1de8_idx'),
        ),
        migrations.AddConstraint(
            model_name='notafiscalitem',
            constraint=models.UniqueConstraint(fields=('nota_fiscal', 'n_item'), name='fiscal_item_unico_por_nf'),
        ),
        migrations.AddConstraint(
            model_name='vinculo',
            constraint=models.UniqueConstraint(fields=('saida_item',), name='fiscal_vinculo_unico_por_item_saida'),
        ),
    ]
