# Generated by Django 5.2.16 on 2026-09-22 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notafiscalitem',
            name='tipo_retorno',
            field=models.CharField(choices=[('DEVOLUCAO_INSUMO', 'Tecido usado/perdido na industrialização (baixa automática)'), ('ENTREGA_PRODUTO', 'Entrega de produto industrializado'), ('NA', 'Não aplicável (item de entrada)')], default='NA', max_length=20),
        ),
    ]
