# Generated by Django 5.2.16 on 2026-09-22 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


_RENOMEIA_MOTIVO = {
    "NF_NAO_ENCONTRADA": "AGUARDANDO_ENTRADA",
    "ITEM_AMBIGUO": "MULTIPLOS_PRODUTOS",
    "ITEM_NAO_ENCONTRADO": "PRODUTO_SEM_CORRESPONDENTE",
    "SALDO_INSUFICIENTE": "QUANTIDADE_EXCEDIDA",
}


def _renomear_motivos_existentes(apps, schema_editor):
    """Os motivos de pendência foram alinhados com os "tipos de divergência"
    do protótipo do fiscal (ver fiscal/models.py::PendenciaMatching.Motivo)
    — remapeia os valores antigos já gravados pros novos nomes."""
    PendenciaMatching = apps.get_model("fiscal", "PendenciaMatching")
    for antigo, novo in _RENOMEIA_MOTIVO.items():
        PendenciaMatching.objects.filter(motivo=antigo).update(motivo=novo)


def _reverter_motivos(apps, schema_editor):
    PendenciaMatching = apps.get_model("fiscal", "PendenciaMatching")
    for antigo, novo in _RENOMEIA_MOTIVO.items():
        PendenciaMatching.objects.filter(motivo=novo).update(motivo=antigo)


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0002_alter_notafiscalitem_tipo_retorno'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(_renomear_motivos_existentes, _reverter_motivos),
        migrations.AddField(
            model_name='notafiscal',
            name='inf_cpl',
            field=models.TextField(blank=True, verbose_name='Informações complementares'),
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='ref_nfe',
            field=models.TextField(blank=True, help_text='Chaves de acesso (44 dígitos) formalmente referenciadas no XML, uma por linha.', verbose_name='NF-e referenciadas'),
        ),
        migrations.AlterField(
            model_name='pendenciamatching',
            name='motivo',
            field=models.CharField(choices=[('AGUARDANDO_ENTRADA', 'Aguardando a NF de entrada citada ser importada'), ('SEM_REFERENCIA', 'Nenhuma referência à NF de entrada encontrada no XML'), ('REF_NAO_IDENTIFICADA', 'Cita uma NF, mas o número não foi identificado com segurança'), ('MULTIPLAS_NF', 'Mais de uma NF de entrada citada na referência'), ('MULTIPLOS_PRODUTOS', 'Mais de um item da entrada é candidato'), ('PRODUTO_SEM_CORRESPONDENTE', 'Nenhum item da entrada corresponde'), ('UNIDADE_INCOMPATIVEL', 'Unidade da saída incompatível com a da entrada'), ('QUANTIDADE_EXCEDIDA', 'Devolução maior que o saldo disponível'), ('TECIDO_NAO_RECONHECIDO', 'Cita uma NF de entrada válida, mas o item não foi reconhecido como tecido'), ('CNPJ_SEM_CLIENTE', 'CNPJ do XML sem Cliente cadastrado')], max_length=30),
        ),
        migrations.CreateModel(
            name='AssociacaoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cprod_saida', models.CharField(max_length=60, verbose_name='Código do produto na saída')),
                ('cprod_entrada', models.CharField(max_length=60, verbose_name='Código do produto na entrada')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associacoes_produto', to='fiscal.cliente')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Associação de produto aprendida',
                'verbose_name_plural': 'Associações de produto aprendidas',
                'constraints': [models.UniqueConstraint(fields=('cliente', 'cprod_saida'), name='fiscal_associacao_unica_por_cliente_produto')],
            },
        ),
    ]
