# Generated by Django 5.2.16 on 2026-09-22 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0003_notafiscal_inf_cpl_notafiscal_ref_nfe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vinculo',
            name='criterio',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
