# Generated by Django 5.2.16 on 2026-09-23 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0005_centro_custo_por_cnpj'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendenciamatching',
            name='itens_entrada',
            field=models.ManyToManyField(blank=True, related_name='pendencias_entrada', to='fiscal.notafiscalitem'),
        ),
    ]
