# Generated by Django 5.2.16 on 2026-09-23 14:55

import re

import django.db.models.deletion
from django.db import migrations, models


def preencher_do_xml(apps, schema_editor):
    """tpNF e autorização das notas já importadas, lidos do xml_bruto. A
    ligação estorno -> nota anulada (ANULADA) fica pro
    `manage.py recalcular_baixas`, que também desfaz as baixas delas."""
    NotaFiscal = apps.get_model("fiscal", "NotaFiscal")
    for nota in NotaFiscal.objects.only("pk", "xml_bruto").iterator():
        x = nota.xml_bruto
        tp = re.search(r"<tpNF>(\d)</tpNF>", x)
        prot = x.split("<protNFe", 1)[1] if "<protNFe" in x else ""
        cstat = re.search(r"<cStat>(\d+)</cStat>", prot)
        autorizada = bool(cstat) and cstat.group(1) in {"100", "150"}
        tp_nf = tp.group(1) if tp else "1"
        situacao = ("NAO_AUTORIZADA" if not autorizada
                    else "ESTORNO" if tp_nf == "0" else "VALIDA")
        NotaFiscal.objects.filter(pk=nota.pk).update(tp_nf=tp_nf, autorizada=autorizada, situacao=situacao)


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0006_pendencia_itens_entrada'),
    ]

    operations = [
        migrations.AddField(
            model_name='notafiscal',
            name='anulada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_anuladas', to='fiscal.notafiscal'),
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='autorizada',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='situacao',
            field=models.CharField(choices=[('VALIDA', 'Válida'), ('NAO_AUTORIZADA', 'Sem autorização de uso (sem protocolo ou cStat recusado)'), ('ESTORNO', 'NF de entrada própria (tpNF=0) — estorno/anulação de outra NF'), ('ANULADA', 'Anulada por NF de estorno'), ('CANCELADA', 'Marcada como cancelada (conferido na SEFAZ)')], db_index=True, default='VALIDA', max_length=20),
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='tp_nf',
            field=models.CharField(blank=True, max_length=1, verbose_name='tpNF'),
        ),
        migrations.AlterField(
            model_name='pendenciamatching',
            name='motivo',
            field=models.CharField(choices=[('AGUARDANDO_ENTRADA', 'Aguardando a NF de entrada citada ser importada'), ('SEM_REFERENCIA', 'Nenhuma referência à NF de entrada encontrada no XML'), ('REF_NAO_IDENTIFICADA', 'Cita uma NF, mas o número não foi identificado com segurança'), ('MULTIPLAS_NF', 'Mais de uma NF de entrada citada na referência'), ('MULTIPLOS_PRODUTOS', 'Mais de um item da entrada é candidato'), ('PRODUTO_SEM_CORRESPONDENTE', 'Nenhum item da entrada corresponde'), ('UNIDADE_INCOMPATIVEL', 'Unidade da saída incompatível com a da entrada'), ('QUANTIDADE_EXCEDIDA', 'Devolução maior que o saldo disponível'), ('POSSIVEL_DUPLICIDADE', 'Possível NF duplicada (confira se uma foi cancelada)'), ('ESTORNO_NAO_CONFERE', 'NF de estorno sem nota anulada correspondente'), ('TECIDO_NAO_RECONHECIDO', 'Cita uma NF de entrada válida, mas o item não foi reconhecido como tecido'), ('CNPJ_SEM_CLIENTE', 'CNPJ do XML sem Cliente cadastrado')], max_length=30),
        ),
        migrations.RunPython(preencher_do_xml, migrations.RunPython.noop),
    ]
