# Generated by Django 5.2.16 on 2026-09-23 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0007_situacao_da_nota'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notafiscal',
            name='cancelamento_detectado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='cancelamento_origem',
            field=models.CharField(blank=True, choices=[('IMPORTACAO', 'Detectado no ato da importação'), ('POS_IMPORTACAO', 'Detectado após a importação (checagem periódica)')], max_length=20),
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='cancelamento_revisado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='cancelamento_revisado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='cancelamento_revisao_pendente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='motivo_cancelamento',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='protocolo_cancelamento',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='situacao_sefaz_verificada_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Verificada na SEFAZ em'),
        ),
        migrations.AddField(
            model_name='notafiscalitem',
            name='excluido_manualmente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pendenciamatching',
            name='nota_fiscal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pendencias_cancelamento', to='fiscal.notafiscal'),
        ),
        migrations.AlterField(
            model_name='notafiscal',
            name='situacao',
            field=models.CharField(choices=[('VALIDA', 'Válida'), ('NAO_AUTORIZADA', 'Sem autorização de uso (sem protocolo ou cStat recusado)'), ('ESTORNO', 'NF de entrada própria (tpNF=0) — estorno/anulação de outra NF'), ('ANULADA', 'Anulada por NF de estorno'), ('CANCELADA', 'Marcada como cancelada (conferido na SEFAZ)'), ('EXCLUIDA', 'Excluída do controle de saldo (decisão manual, não confirmada como cancelada)')], db_index=True, default='VALIDA', max_length=20),
        ),
        migrations.AlterField(
            model_name='pendenciamatching',
            name='motivo',
            field=models.CharField(choices=[('AGUARDANDO_ENTRADA', 'Aguardando a NF de entrada citada ser importada'), ('SEM_REFERENCIA', 'Nenhuma referência à NF de entrada encontrada no XML'), ('REF_NAO_IDENTIFICADA', 'Cita uma NF, mas o número não foi identificado com segurança'), ('MULTIPLAS_NF', 'Mais de uma NF de entrada citada na referência'), ('MULTIPLOS_PRODUTOS', 'Mais de um item da entrada é candidato'), ('PRODUTO_SEM_CORRESPONDENTE', 'Nenhum item da entrada corresponde'), ('UNIDADE_INCOMPATIVEL', 'Unidade da saída incompatível com a da entrada'), ('QUANTIDADE_EXCEDIDA', 'Devolução maior que o saldo disponível'), ('POSSIVEL_DUPLICIDADE', 'Possível NF duplicada (confira se uma foi cancelada)'), ('ESTORNO_NAO_CONFERE', 'NF de estorno sem nota anulada correspondente'), ('TECIDO_NAO_RECONHECIDO', 'Cita uma NF de entrada válida, mas o item não foi reconhecido como tecido'), ('CNPJ_SEM_CLIENTE', 'CNPJ do XML sem Cliente cadastrado'), ('CANCELADA_SEFAZ', 'SEFAZ reporta esta NF como cancelada (detectado após a importação)')], max_length=30),
        ),
    ]
