# Generated by Django 5.2.16 on 2026-09-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0010_seed_centros_custo'),
    ]

    operations = [
        migrations.AddField(
            model_name='centrocusto',
            name='uf',
            field=models.CharField(
                default='SP', max_length=2, verbose_name='UF',
                help_text='Estado emissor das NF-e desta unidade — decide o endpoint da SEFAZ na '
                          'consulta de cancelamento (fiscal/sefaz.py). Só SP tem endpoint cadastrado '
                          'por enquanto.'),
        ),
    ]
