# Generated by Django 5.2.16 on 2026-07-27 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegraPremiacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidade', models.CharField(choices=[('GGTTEX_JOGOS', 'GGTTEX Jogos'), ('GGTTEX_FRONHA', 'GGTTEX Fronha')], max_length=20)),
                ('atividade', models.CharField(choices=[('COSTURA_CANTO', 'Costura de Canto'), ('COSTURA_ELASTICO', 'Costura de Elástico'), ('COSTURA_RETA', 'Costura Reta'), ('DOBRA_FUNDO', 'Dobra de Fundo'), ('DOBRA_EMPAPELA', 'Dobra e Empapela'), ('CASEADO', 'Caseado'), ('EMBALAGEM', 'Embalagem'), ('BAINHA_FECHAMENTO', 'Bainha ou Fechamento'), ('ESTICADO', 'Esticado'), ('DESVIRADO', 'Desvirado')], max_length=30)),
                ('usa_tamanho', models.BooleanField(default=False, help_text='Marque só para atividades cuja meta depende do tamanho (Solteiro/Casal/Queen) produzido no dia.', verbose_name='Meta varia por tamanho')),
                ('meta_solteiro', models.PositiveIntegerField(blank=True, null=True, verbose_name='Meta — Solteiro (peças/dia)')),
                ('meta_casal', models.PositiveIntegerField(blank=True, null=True, verbose_name='Meta — Casal (peças/dia)')),
                ('meta_queen', models.PositiveIntegerField(blank=True, null=True, verbose_name='Meta — Queen (peças/dia)')),
                ('meta_tamanhos_mistos', models.PositiveIntegerField(blank=True, help_text='Usada quando o colaborador produz mais de um tamanho na mesma atividade no mesmo dia.', null=True, verbose_name='Meta — mais de um tamanho no dia (peças/dia)')),
                ('meta_padrao', models.PositiveIntegerField(blank=True, help_text='Usada quando a atividade não varia por tamanho.', null=True, verbose_name='Meta padrão (peças/dia)')),
                ('valor_peca_excedente', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Valor por peça excedente (R$)')),
                ('vigente_desde', models.DateField(verbose_name='Vigente desde')),
                ('vigente_ate', models.DateField(blank=True, help_text='Deixe em branco se ainda está em vigor.', null=True, verbose_name='Vigente até')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Regra de premiação',
                'verbose_name_plural': 'Regras de premiação',
                'ordering': ['unidade', 'atividade', '-vigente_desde'],
            },
        ),
    ]
