"""
Django settings for central project.

Generated by 'django-admin startproject' using Django 5.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Lê variáveis de ambiente de um .env na raiz (nunca commitado — ver .env.example).
env = environ.Env(DJANGO_DEBUG=(bool, False))
environ.Env.read_env(BASE_DIR / '.env')

# Liga/desliga a Gestão de OP (controle_op) sem precisar de deploy novo —
# ainda em desenvolvimento, não deve ficar acessível em produção enquanto
# não estiver pronta. Desligada por padrão: a app fica instalada (migrações
# rodam normalmente) mas a rota /controle-op/ (central/urls.py) e a entrada
# de menu (paineis/modulos.py) somem quando a flag está off — não é só o
# menu escondido, a URL deixa de existir mesmo. Mesmo padrão de RUN_SCHEDULER
# (integracao/scheduler.py). Pra testar localmente: GESTAO_OP_HABILITADA=True no .env.
GESTAO_OP_HABILITADA = env.bool('GESTAO_OP_HABILITADA', default=False)

# SECURITY WARNING: keep the secret key used in production secret!
# Vem do .env. Em produção, gere uma chave nova (nunca reaproveite a de dev)
# e defina só via variável de ambiente do servidor — nunca no código.
SECRET_KEY = env('DJANGO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DJANGO_DEBUG')

# Vazio + DEBUG=True já libera localhost/127.0.0.1. Para produção, define
# DJANGO_ALLOWED_HOSTS no .env do servidor com o(s) domínio(s) reais.
ALLOWED_HOSTS = env.list(
    'DJANGO_ALLOWED_HOSTS',
    default=['localhost', '127.0.0.1', '192.168.0.199', '192.168.0.60'],
)

# Necessário quando o app roda atrás de HTTPS em produção (o Django exige a
# origem completa, com esquema, a partir da 4.x).
CSRF_TRUSTED_ORIGINS = env.list('DJANGO_CSRF_TRUSTED_ORIGINS', default=[])

# Base fixa pra montar links absolutos mandados pra fora do sistema (ex.:
# o link do prestador disparado por WhatsApp, controle_op/views.py::
# disparo_prestadores) — NUNCA usar request.build_absolute_uri() pra isso:
# ele monta a URL com o host de quem está navegando na hora (se for alguém
# testando local, o prestador recebe um link pra 127.0.0.1, que não existe
# no celular dele e o WhatsApp nem reconhece como link clicável).
SITE_URL = env('SITE_URL', default='http://127.0.0.1:8000')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    # apps do projeto
    'paineis',
    'contas',
    'integracao',
    'producao',
    'relatorios',
    'frete',
    'corte',
    'carteira',
    'cargas',
    'programacao',
    'metas',
    'controle_op',
    'fiscal',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # As de baixo rodam depois do AuthenticationMiddleware de propósito —
    # precisam de request.user/request.session já resolvidos (ver
    # central/middleware.py e contas/middleware.py).
    'central.middleware.SessaoExpiradaMiddleware',
    'central.middleware.RateLimitMiddleware',
    'contas.middleware.SetorAccessMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'central.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'paineis.context_processors.navegacao',
            ],
        },
    },
]

WSGI_APPLICATION = 'central.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# Lida do DATABASE_URL no .env (formato: postgres://usuario:senha@host:porta/nome).
# Obrigatório — todos os dados (auth, negócio, sync) já vivem só no Postgres
# desde a migração; sem essa variável o app deve falhar alto e claro em vez
# de cair silenciosamente num SQLite antigo e desatualizado.

DATABASES = {'default': env.db('DATABASE_URL')}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True

USE_THOUSAND_SEPARATOR = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
# Onde `collectstatic` junta tudo pra produção — o Whitenoise serve direto
# daqui (comprimido + com hash no nome do arquivo pra cache eterno no navegador).
STATIC_ROOT = BASE_DIR / 'staticfiles'
STORAGES = {
    'default': {'BACKEND': 'django.core.files.storage.FileSystemStorage'},
    'staticfiles': {'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage'},
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Autenticação
# Login ignora maiúsculas/minúsculas no usuário (só na checagem — o cadastro
# no admin continua salvando exatamente como foi digitado).
AUTHENTICATION_BACKENDS = ['contas.backends.CaseInsensitiveModelBackend']

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'paineis:home'
LOGOUT_REDIRECT_URL = 'login'

# Sessão: NÃO dá pra confiar em "fechou o navegador/app" pra derrubar a
# sessão — testado 2026-08-03: no PWA instalado no Windows, o Edge tem uma
# opção padrão de "continuar rodando em segundo plano" que faz o processo do
# navegador nunca morrer de verdade, então SESSION_EXPIRE_AT_BROWSER_CLOSE
# nunca dispara e o cookie de sessão nunca é limpo.
#
# Troca de estratégia: o cookie tem vida CURTA (poucos minutos) e é renovado
# sozinho por um "sinal de vida" em JS (ver templates/base.html +
# contas/views.py::heartbeat) a cada 2 min, enquanto a aba/app estiver
# aberta — qualquer request autenticado também renova (SESSION_SAVE_
# EVERY_REQUEST). Fechando de verdade, os sinais param e o cookie expira
# sozinho em poucos minutos, sem depender de o navegador perceber nada.
# Por cima disso, SessaoExpiradaMiddleware força logout depois de 2h desde o
# login, não importa quanta renovação tenha acontecido (rede de segurança
# contra sessão renovada pra sempre com a aba esquecida aberta o dia todo).
SESSION_COOKIE_AGE = 60 * 8  # 8 minutos — renovado por atividade/heartbeat
SESSION_SAVE_EVERY_REQUEST = True
SESSAO_LIMITE_ABSOLUTO_SEGUNDOS = 60 * 60 * 2  # 2 horas desde o login

# Segurança de cookies e headers.
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = 'Lax'

# HTTPS: só força quando não está em DEBUG (dev local roda em HTTP puro).
# No Fly.io o TLS termina no proxy da borda — a requisição chega no container
# em HTTP puro com X-Forwarded-Proto indicando o protocolo original. Sem isso,
# SECURE_SSL_REDIRECT entra em loop infinito (acha que toda requisição é HTTP).
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
SECURE_SSL_REDIRECT = not DEBUG
SECURE_REFERRER_POLICY = 'same-origin'
SECURE_CONTENT_TYPE_NOSNIFF = True
if not DEBUG:
    # Ativa HSTS gradualmente: comece baixo, confirme que o HTTPS está
    # estável em produção, depois suba para 31536000 (1 ano) e considere
    # include_subdomains/preload.
    SECURE_HSTS_SECONDS = 3600
    SECURE_HSTS_INCLUDE_SUBDOMAINS = False
    SECURE_HSTS_PRELOAD = False

# Sem isso, com DEBUG=False o Django só manda o traceback de um erro 500 por
# e-mail pros ADMINS (que nem estão configurados) — nada aparecia no
# `fly logs`, e o erro ficava invisível.
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {'console': {'class': 'logging.StreamHandler'}},
    'loggers': {
        'django.request': {'handlers': ['console'], 'level': 'ERROR', 'propagate': False},
    },
}

# Integração — cache das planilhas Google Sheets (leitura ao vivo)
SHEETS_CACHE_DIR = BASE_DIR / 'cache' / 'sheets'

# E-mail — alerta diário de lançamento (Corte, Produção), ver
# relatorios/cron.py. Backend console em DEBUG pra não exigir SMTP em dev.
EMAIL_BACKEND = (
    'django.core.mail.backends.console.EmailBackend' if DEBUG
    else 'django.core.mail.backends.smtp.EmailBackend'
)
EMAIL_HOST = env.str('EMAIL_HOST', default='')
EMAIL_PORT = env.int('EMAIL_PORT', default=587)
EMAIL_HOST_USER = env.str('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = env.str('EMAIL_HOST_PASSWORD', default='')
EMAIL_USE_TLS = env.bool('EMAIL_USE_TLS', default=True)
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# Token do endpoint de cron (relatorios/cron.py) chamado pelo GitHub Actions —
# NUNCA no código, só via secret (fly secrets set / .env local).
REPORT_TRIGGER_TOKEN = env.str('REPORT_TRIGGER_TOKEN', default='')
RELATORIOS_EMAIL_TO = env.list('RELATORIOS_EMAIL_TO', default=[])

# Limite padrão do Django (5.1+) é 100 arquivos por request — baixo demais
# pro import de NF-e do Fiscal, que sobe centenas/milhares de XMLs de uma vez
# (ver fiscal/views.py::_etapa1_upload, request.FILES.getlist("arquivos")).
# Sem isso, upload de lote grande vira 400 Bad Request (RequestDataTooBig)
# antes até de entrar na view. 50 mil dá bastante margem acima do maior lote
# já visto (~30 mil).
DATA_UPLOAD_MAX_NUMBER_FILES = 50000

# Saldo Fiscal (app `fiscal`) — CNPJs da Zanattex (mais de uma unidade/razão
# social conta como "nós", ex.: Mega Preven — cada CNPJ vira um centro de
# custo diferente, ver fiscal/importador.py::identificar_nota), usados pra
# decidir se uma NF-e importada é ENTRADA (Zanattex é o destinatário) ou
# SAÍDA (Zanattex é o emitente). Só dígitos, igual ao conteúdo da tag
# <CNPJ> do XML da NF-e.
FISCAL_CNPJS_ZANATTEX = set(env.list(
    'FISCAL_CNPJS_ZANATTEX', default=['14601572000130', '64030122000103']))

# NCMs tratados como "tecido" pro controle de saldo/consumo automático — v1
# só controla o tecido em si, não os insumos de produção que vêm junto na
# mesma NF (etiqueta, embalagem plástica etc.), que ficam de fora do saldo
# e do casamento automático até o controle desses ser implementado junto
# com o almoxarife. Ampliar essa lista é como estender o controle depois.
# 60019200 = tecido em KG; 54075210 = tecido em MT (ex.: "TEC.MICROFIBRA...");
# 52085100 = tecido em MT (ex.: "TECIDO 120 FIOS ESTAMPADO...");
# 54075400 = tecido em MT (ex.: "TEC. MICROFIBRA EST. 65G/M2 ... LARG.2,25") —
# faltava: sem saldo, a devolução dele caía no outro microfibra da mesma NF.
# Mudou a lista? Rodar `manage.py recalcular_baixas --aplicar` depois.
FISCAL_NCMS_CONTROLADOS = set(env.list(
    'FISCAL_NCMS_CONTROLADOS', default=['60019200', '54075210', '52085100', '54075400']))

# Consulta ao SEFAZ (fiscal/sefaz.py) pra detectar NF-e canceladas — ver
# plano em memory/sefaz-cancelamento-plano.md. Fase 1 (barramento no ato da
# importação) só precisa da UF/certificado da Zanattex; os demais centros de
# custo entram depois, um a um, sem mudar nenhuma dessas settings.
#
# UF de cada CNPJ (todos em SP por enquanto, confirmado pelo usuário) — usado
# pra resolver o endpoint SOAP certo (fiscal/sefaz.py::_ENDPOINTS_POR_UF).
FISCAL_SEFAZ_UF_POR_CNPJ = {
    cnpj: uf for cnpj, uf in
    (par.split(':') for par in env.list('FISCAL_SEFAZ_UF_POR_CNPJ', default=[
        '14601572000130:SP', '64030122000103:SP']))
}
# homologacao / producao — sempre começar em homologação até validar contra
# uma chave de acesso conhecida (ver management command verificar_cancelamentos_sefaz).
FISCAL_SEFAZ_AMBIENTE = env.str('FISCAL_SEFAZ_AMBIENTE', default='homologacao')
# Certificados A1 por CNPJ, nunca em disco — um secret JSON só (base64),
# {"<cnpj>": {"pfx_b64": "...", "senha": "..."}, ...}. CNPJ sem entrada aqui
# vira "não verificada" na consulta (não erro), até o certificado dele entrar.
FISCAL_SEFAZ_CERTIFICADOS_JSON = env.str('FISCAL_SEFAZ_CERTIFICADOS_JSON', default='')
# Teto por chamada SOAP individual (segundos) e nº de consultas em paralelo
# por lote (ThreadPoolExecutor) — é o que evita que a checagem no ato do
# import estoure o corte de 60s do proxy do Fly (ver fly-proxy-60s-lotes).
FISCAL_SEFAZ_TIMEOUT_SEGUNDOS = env.float('FISCAL_SEFAZ_TIMEOUT_SEGUNDOS', default=3.0)
FISCAL_SEFAZ_MAX_PARALELO = env.int('FISCAL_SEFAZ_MAX_PARALELO', default=10)
# Quantas notas a checagem periódica processa por rodada (fiscal/sefaz_servico.py,
# Fase 2) — sem filtro de janela de dias, então isso é o teto que evita uma
# rodada monstro logo após a remontagem de dados em produção.
FISCAL_SEFAZ_LOTE_CRON = env.int('FISCAL_SEFAZ_LOTE_CRON', default=200)

# Teto visível pro usuário de quantos arquivos entram numa mesma sessão de
# upload (fiscal/forms.py::UploadXmlForm) — distinto dos lotes internos
# _TAMANHO_LOTE/_TAMANHO_LOTE_CONFIRMACAO de fiscal/views.py (que continuam
# fatiando por baixo, sem o usuário ver). Existe pra forçar sessões menores e
# deliberadas na remontagem de dados em produção, já que cada nota agora bate
# no SEFAZ durante a importação.
FISCAL_MAX_ARQUIVOS_POR_ENVIO = env.int('FISCAL_MAX_ARQUIVOS_POR_ENVIO', default=500)
